site_name: Reference Docs
site_url: 
site_description: Documentation for all references.
site_author: Sathesh Purushothaman

repo_url: 
edit_uri: ""

theme:
    name: material
    #name: windmill
    #name: ivory
    highlightjs: true
    include_homepage_in_sidebar: true
    prev_next_buttons_location: bottom
    navigation_depth: 4
    collapse_navigation: true
    titles_only: false
    sticky_navigation: true
    hljs_languages:
        - yaml
        - rust

nav:
    - Home: index.md
    - About:
        - Release: about/about.md
    - Builds and Scripts:
        - Bash: build-and-scripts/bash.md
        - Gradle: build-and-scripts/gradle.md
        - network: build-and-scripts/network.md
        - SSH: build-and-scripts/ssh.md
    - Container:
        - Docker: container/docker.md
        - Helm: container/helm.md
        - Kubernetes: container/kubernetes.md
        - Minikube: container/minikube.md
    - Diagrams:
        - PlantUML: diagrams/diagrams.md
    - Links:
        - AwsCli: links/aws-cli.md
        - LetsEncrypt: links/letsencrypt.md
        - Mac Softwares: links/mac-softwares.md
        - MkDocs: links/mkdocs.md
    - Servers:
        - DynamoDB: servers/dynamodb.md
        - ElasticSearch: servers/elasticsearch.md
        - Kafka: servers/kafka.md
        - Kibana: servers/kibana.md
        - MongoDB: servers/mongodb.md
        - Nginx: servers/nginx.md
        - Redis: servers/redis.md
    - Service-discovery:
        - Aws cloud map: service-discovery/aws-cloud-map.md
        - Consul: service-discovery/consul.md
        - Eureka: service-discovery/eureka.md
    - Skills:
        - TechStack: skills/techstack.md
    - Spring:
        - Spring-boot: spring/spring-boot.md

markdown_extensions:
    - attr_list

plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
